branches:
  only:
  - master
  - alberto-patch

language: python

python:
  - "3.6" # current default Python on Travis CI
  - "3.7" 
  - "3.8" # highest python version supported by Django

services:
  - postgresql

env:
  - DJANGO="Django>=3"

install: # command to install dependencies
    - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script: # command to run tests
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runserver &

after_script:
  - pkill -f runserver

notifications: # when tests are developed, they should be placed here
  slack: sddspaghetticode:NyaUgvSVibaHRlBFifCvP6Lw
